mutation createTransaction($student_id:String!,$bill_id:String!,$use:String!){
	payment_transaction_create(
                student_id : $student_id,
                bill_id : $bill_id,
                use : $use
	) {
                snap_token,
                redirect_url
        }
}