query getListTransaction($search_by:String!,$search_value:String!,$order_by:String!,$order_dir:String!,$offset:Int!,$limit:Int!){
		transaction_list(
            search_by : $search_by,
            search_value : $search_value,
            order_by:$order_by,
            order_dir:$order_dir,
            offset:$offset,
            limit:$limit
		)
		{
			id,
			bill_id,
			student_id,
			amount,
			payment_status,
			payment_id,
			payment_time,
			approval_code,
			payment_type
		}
}