query getListBill($show_actual_total:Boolean!,$search_by:String!,$search_value:String!,$order_by:String!,$order_dir:String!,$offset:Int!,$limit:Int!){
    bill_list(
        show_actual_total : $show_actual_total,
        search_by : $search_by,
        search_value : $search_value,
        order_by:$order_by,
        order_dir:$order_dir,
        offset:$offset,
        limit:$limit
    )
    {
        id,
        student_id,
        name,
        detail,
        amount,
        due_date,
        bill_status
    }
}
	