query santriLogin($nis:String!,$password:String!){
    santri_login(
            nis : $nis,
            password : $password
        ) {
            id,
            santri_id,
            session_data
        }
}