query getUnpayBillDetail($student_id:String!){
    unpay_bill_detail(
            student_id:$student_id
        ) {
            id,
            student_id,
            name,
            detail,
            amount,
            due_date,
            bill_status
        }
}