mutation updatePayedBill($id:String!,$santri_id : String!,$name:String!,$detail:String!,$amount:String!,$due_date:String!,$bill_status:Int!){
    bill_update(
            id : $id,
            santri_id : $santri_id,
            name : $name,
            detail : $detail,
            amount : $amount,
            due_date : $due_date
            bill_status : $bill_status 
        ) {
            id
        }
}